// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: blocklist.sql

package db

import (
	"context"
)

const insertBlockedID = `-- name: InsertBlockedID :exec
INSERT INTO blocked_ids(id, updated_at)
VALUES ($1, NOW())
ON CONFLICT (id) DO UPDATE
SET updated_at = NOW()
`

func (q *Queries) InsertBlockedID(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, insertBlockedID, id)
	return err
}

const isBlocked = `-- name: IsBlocked :one
SELECT EXISTS (
    SELECT 1 FROM blocked_ids WHERE id = $1
) AS blocked
`

func (q *Queries) IsBlocked(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, isBlocked, id)
	var blocked bool
	err := row.Scan(&blocked)
	return blocked, err
}
