// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: campaigns.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getCampaignByLinkID = `-- name: GetCampaignByLinkID :one
SELECT campaign_id, name, start_date, end_date, status, target_url, link_id FROM campaigns
WHERE link_id = $1
LIMIT 1
`

func (q *Queries) GetCampaignByLinkID(ctx context.Context, linkID uuid.UUID) (Campaign, error) {
	row := q.db.QueryRow(ctx, getCampaignByLinkID, linkID)
	var i Campaign
	err := row.Scan(
		&i.CampaignID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.TargetUrl,
		&i.LinkID,
	)
	return i, err
}
