// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: click.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countClicksByIPInLast60Seconds = `-- name: CountClicksByIPInLast60Seconds :one
SELECT COUNT(*) as click_count
FROM clicks
WHERE ip_address = $1
  AND timestamp > NOW() - INTERVAL '60 seconds'
`

func (q *Queries) CountClicksByIPInLast60Seconds(ctx context.Context, ipAddress pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countClicksByIPInLast60Seconds, ipAddress)
	var click_count int64
	err := row.Scan(&click_count)
	return click_count, err
}

const insertClick = `-- name: InsertClick :exec
INSERT INTO clicks (
    click_id, 
    timestamp, 
    link_id, 
    campaign_id, 
    user_id,
    ip_address,
    user_agent,
    referrer,
    device,
    device_model,
    browser,
    gaid,
    idfa,
    geo_country,
    geo_state,
    status,
    fraud_check_failed
) VALUES (
    $1,
    NOW(),
    $2, 
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16
)
`

type InsertClickParams struct {
	ClickID          uuid.UUID   `json:"click_id"`
	LinkID           uuid.UUID   `json:"link_id"`
	CampaignID       uuid.UUID   `json:"campaign_id"`
	UserID           string      `json:"user_id"`
	IpAddress        pgtype.Text `json:"ip_address"`
	UserAgent        pgtype.Text `json:"user_agent"`
	Referrer         pgtype.Text `json:"referrer"`
	Device           pgtype.Text `json:"device"`
	DeviceModel      pgtype.Text `json:"device_model"`
	Browser          pgtype.Text `json:"browser"`
	Gaid             pgtype.Text `json:"gaid"`
	Idfa             pgtype.Text `json:"idfa"`
	GeoCountry       pgtype.Text `json:"geo_country"`
	GeoState         pgtype.Text `json:"geo_state"`
	Status           ClickStatus `json:"status"`
	FraudCheckFailed []string    `json:"fraud_check_failed"`
}

func (q *Queries) InsertClick(ctx context.Context, arg InsertClickParams) error {
	_, err := q.db.Exec(ctx, insertClick,
		arg.ClickID,
		arg.LinkID,
		arg.CampaignID,
		arg.UserID,
		arg.IpAddress,
		arg.UserAgent,
		arg.Referrer,
		arg.Device,
		arg.DeviceModel,
		arg.Browser,
		arg.Gaid,
		arg.Idfa,
		arg.GeoCountry,
		arg.GeoState,
		arg.Status,
		arg.FraudCheckFailed,
	)
	return err
}
