// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CampaignStatus string

const (
	CampaignStatusActive CampaignStatus = "active"
	CampaignStatusPaused CampaignStatus = "paused"
)

func (e *CampaignStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CampaignStatus(s)
	case string:
		*e = CampaignStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CampaignStatus: %T", src)
	}
	return nil
}

type NullCampaignStatus struct {
	CampaignStatus CampaignStatus `json:"campaign_status"`
	Valid          bool           `json:"valid"` // Valid is true if CampaignStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCampaignStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CampaignStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CampaignStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCampaignStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CampaignStatus), nil
}

type ClickStatus string

const (
	ClickStatusAllowed ClickStatus = "allowed"
	ClickStatusFraud   ClickStatus = "fraud"
	ClickStatusError   ClickStatus = "error"
)

func (e *ClickStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ClickStatus(s)
	case string:
		*e = ClickStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ClickStatus: %T", src)
	}
	return nil
}

type NullClickStatus struct {
	ClickStatus ClickStatus `json:"click_status"`
	Valid       bool        `json:"valid"` // Valid is true if ClickStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullClickStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ClickStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ClickStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullClickStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ClickStatus), nil
}

type BlockedID struct {
	ID        string           `json:"id"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Campaign struct {
	CampaignID uuid.UUID        `json:"campaign_id"`
	Name       string           `json:"name"`
	StartDate  pgtype.Timestamp `json:"start_date"`
	EndDate    pgtype.Timestamp `json:"end_date"`
	Status     CampaignStatus   `json:"status"`
	TargetUrl  string           `json:"target_url"`
	LinkID     uuid.UUID        `json:"link_id"`
}

type Click struct {
	ClickID          uuid.UUID        `json:"click_id"`
	Timestamp        pgtype.Timestamp `json:"timestamp"`
	LinkID           uuid.UUID        `json:"link_id"`
	CampaignID       uuid.UUID        `json:"campaign_id"`
	UserID           string           `json:"user_id"`
	IpAddress        pgtype.Text      `json:"ip_address"`
	UserAgent        pgtype.Text      `json:"user_agent"`
	Referrer         pgtype.Text      `json:"referrer"`
	Device           pgtype.Text      `json:"device"`
	DeviceModel      pgtype.Text      `json:"device_model"`
	Browser          pgtype.Text      `json:"browser"`
	Gaid             pgtype.Text      `json:"gaid"`
	Idfa             pgtype.Text      `json:"idfa"`
	GeoCountry       pgtype.Text      `json:"geo_country"`
	GeoState         pgtype.Text      `json:"geo_state"`
	Status           ClickStatus      `json:"status"`
	FraudCheckFailed []string         `json:"fraud_check_failed"`
}
